import requests
import json
from datetime import datetime, timezone
import time

URL = "https://www.intermarche.pt/api/service/produits/v4/pdvs/07348/products/byKeywordAndCategory"

HEADERS = {
    "accept": "application/json, text/plain, */*",
    "accept-language": "pt-PT,pt;q=0.9,en-US;q=0.8,en;q=0.7",
    "cache-control": "no-cache",
    "content-type": "application/json;charset=UTF-8",
    "origin": "https://www.intermarche.pt",
    "pragma": "no-cache",
    "priority": "u=1, i",
    "referer": "https://www.intermarche.pt/shelves/talho-e-peixaria/talho/porco/11539",
    "sec-ch-device-memory": "8",
    "sec-ch-ua": '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
    "sec-ch-ua-arch": '"arm"',
    "sec-ch-ua-full-version-list": '"Not:A-Brand";v="99.0.0.0", "Google Chrome";v="145.0.7632.160", "Chromium";v="145.0.7632.160"',
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-model": '""',
    "sec-ch-ua-platform": '"macOS"',
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "same-origin",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36",
    "x-itm-device-fp": "9961d4b8-18c0-4f5d-ae56-6cb6ea9a8347",
    "x-itm-session-id": "c4203fe4-7625-41e4-bff7-20a0126868b7",
    "x-optional-oauth": "true",
    "x-pdv": '{"ref":"07348","isEcommerce":true}',
    "x-red-device": "red_fo_desktop",
    "x-red-version": "3",
    "x-service-name": "produits"
}

COOKIES = {
    "_ga": "GA1.1.161928546.1772848549",
    "itm_device_id": "9961d4b8-18c0-4f5d-ae56-6cb6ea9a8347",
    "itm_usid": "c4203fe4-7625-41e4-bff7-20a0126868b7",
    "datadome": "JLjZJak0fdou5pVHIhEMGRUDFW1V1toqr5I5oc6Zxi2~xWsntwixVXd30gj6yZoydFDR1adftsi~PsffaWOOlo6Uk9uf4PCzgzzm7hL28eoUKqJVowO3DvnsFXvCed8N"
}

targetUrls = [
        "https://www.intermarche.pt/shelves/talho-e-peixaria/talho/porco/11539",
        "https://www.intermarche.pt/shelves/talho-e-peixaria/talho/novilho-vitela-e-vitelao/11540",
        "https://www.intermarche.pt/shelves/talho-e-peixaria/talho/borrego-e-cabrito/11541",
        "https://www.intermarche.pt/shelves/talho-e-peixaria/talho/coelho/11542",
        "https://www.intermarche.pt/shelves/talho-e-peixaria/talho/aves/11543",
        "https://www.intermarche.pt/shelves/talho-e-peixaria/talho/salsichas-especialidades-e-preparados/11544",
        "https://www.intermarche.pt/shelves/talho-e-peixaria/peixaria/bacalhau/11545",
        "https://www.intermarche.pt/shelves/talho-e-peixaria/peixaria/peixe/11546",
        "https://www.intermarche.pt/shelves/talho-e-peixaria/peixaria/marisco/11547",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/macas-e-peras/11508",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/laranjas-e-outros-citrinos/11510",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/bananas-e-kiwis/11511",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/pessegos-nectarinas-e-ameixas/11512",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/limoes-e-limas/11509",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/ananas-e-abacaxi/11513",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/frutos-vermelhos/11514",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/uvas/11515",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/melao-meloa-e-melancia/11516",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/outros-frutos-da-epoca/11517",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/frutas-tropicais-e-exoticas/11518",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/frutas/frutos-secos-e-desidratados/11519",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/legumes-e-saladas-embaladas/11532",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/alfaces-e-rucula/11531",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/batatas/11522",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/cebolas-e-alhos/11523",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/couves-e-feijao-verde/11524",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/nabos-e-grelos/11525",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/agriao-e-alho-frances/11526",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/cenouras-e-abobora/11527",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/tomates-e-pimentos/11528",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/pepinos-e-curgetes/11530",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/cogumelos/11529",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/ervas-aromaticas/11534",
        "https://www.intermarche.pt/shelves/frutas-e-legumes/legumes/outros-legumes/11533",
        "https://www.intermarche.pt/shelves/mercearia/arroz-massa-e-farinha/arroz/11715",
        "https://www.intermarche.pt/shelves/mercearia/arroz-massa-e-farinha/massa/11716",
        "https://www.intermarche.pt/shelves/mercearia/arroz-massa-e-farinha/farinha/11717",
        "https://www.intermarche.pt/shelves/mercearia/azeite-oleo-e-vinagre/azeite/11718",
        "https://www.intermarche.pt/shelves/mercearia/azeite-oleo-e-vinagre/oleo-alimentar/11719",
        "https://www.intermarche.pt/shelves/mercearia/azeite-oleo-e-vinagre/vinagre/11720",
        "https://www.intermarche.pt/shelves/mercearia/molhos-temperos-e-sal/molhos/11721",
        "https://www.intermarche.pt/shelves/mercearia/molhos-temperos-e-sal/temperos/11757",
        "https://www.intermarche.pt/shelves/mercearia/molhos-temperos-e-sal/maionese-ketchup-e-mostarda/11722",
        "https://www.intermarche.pt/shelves/mercearia/molhos-temperos-e-sal/especiarias-e-ervas-aromaticas/11723",
        "https://www.intermarche.pt/shelves/mercearia/molhos-temperos-e-sal/caldos/11724",
        "https://www.intermarche.pt/shelves/mercearia/molhos-temperos-e-sal/sal/11725",
        "https://www.intermarche.pt/shelves/mercearia/vegetais-secos-e-sementes/feijao/10242",
        "https://www.intermarche.pt/shelves/mercearia/vegetais-secos-e-sementes/grao/10243",
        "https://www.intermarche.pt/shelves/mercearia/vegetais-secos-e-sementes/sementes/11817",
        "https://www.intermarche.pt/shelves/mercearia/cafe-cha-e-achocolatados/cafe-em-capsulas/10273",
        "https://www.intermarche.pt/shelves/mercearia/cafe-cha-e-achocolatados/cafe-torrado/11058",
        "https://www.intermarche.pt/shelves/mercearia/cafe-cha-e-achocolatados/cafe-soluvel/10271",
        "https://www.intermarche.pt/shelves/mercearia/cafe-cha-e-achocolatados/bebidas-de-cereais/11057",
        "https://www.intermarche.pt/shelves/mercearia/cafe-cha-e-achocolatados/chas-e-infusoes/11736",
        "https://www.intermarche.pt/shelves/mercearia/cafe-cha-e-achocolatados/chocolate-em-po/11745",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/acucar-e-adocantes/10292",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/chocolate-e-cacau-de-culinaria/11737",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/farinha-e-fermento/11738",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/aromas-toppings-e-corantes/11739",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/gelatinas/11740",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/bolos-e-sobremesas/11741",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/coberturas-e-decoracao/11742",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/leite-condensado/11743",
        "https://www.intermarche.pt/shelves/mercearia/acucar-e-sobremesas/fruta-em-calda/11744",
        "https://www.intermarche.pt/shelves/mercearia/cereais-e-barras/cereais-infantis-e-juvenis/10260",
        "https://www.intermarche.pt/shelves/mercearia/cereais-e-barras/cereais-linha-e-fibra/11050",
        "https://www.intermarche.pt/shelves/mercearia/cereais-e-barras/muesli-e-granola/11052",
        "https://www.intermarche.pt/shelves/mercearia/cereais-e-barras/flocos-e-papas/11053",
        "https://www.intermarche.pt/shelves/mercearia/cereais-e-barras/barras-de-cereais/11054",
        "https://www.intermarche.pt/shelves/mercearia/cremes-de-barrar-doces-e-mel/doces-e-compotas/11072",
        "https://www.intermarche.pt/shelves/mercearia/cremes-de-barrar-doces-e-mel/marmelada-e-goiabada/10318",
        "https://www.intermarche.pt/shelves/mercearia/cremes-de-barrar-doces-e-mel/cremes-de-barrar/10317",
        "https://www.intermarche.pt/shelves/mercearia/cremes-de-barrar-doces-e-mel/mel/10319",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolachas-de-chocolate/11082",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolachas-com-cobertura-e-recheio/10796",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolachas-infantis/10251",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolachas-de-manteiga-shortcake-e-palmiers/11747",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolachas-maria-e-torrada/10253",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolachas-cracker-e-agua-e-sal/10250",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolachas-fibra-e-sem-acucar/10252",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolos-napolitanas-e-paes-de-leite/10259",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/bolachas-sortidas/11750",
        "https://www.intermarche.pt/shelves/mercearia/bolachas-biscoitos-e-bolos/tortitas-arroz-e-milho/11816",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/chocolates-de-leite/10306",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/chocolates-negros/10746",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/chocolates-brancos/10747",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/chocolate-com-avela-e-amendoa/10751",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/bombons/10304",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/chocolates-mini-e-drageias/10308",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/chocolate-com-recheios-de-fruta/10307",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/chocolate-infantil/10305",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/gomas-e-rebucados/11748",
        "https://www.intermarche.pt/shelves/mercearia/chocolate-gomas-e-rebucados/pastilhas-elasticas/11749",
        "https://www.intermarche.pt/shelves/mercearia/conservas/azeitonas-e-tremocos/11727",
        "https://www.intermarche.pt/shelves/mercearia/conservas/cogumelos-milho-e-ervilhas/11728",
        "https://www.intermarche.pt/shelves/mercearia/conservas/feijao-e-grao/11729",
        "https://www.intermarche.pt/shelves/mercearia/conservas/peixe/11730",
        "https://www.intermarche.pt/shelves/mercearia/conservas/salsichas/11731",
        "https://www.intermarche.pt/shelves/mercearia/conservas/pate/11732",
        "https://www.intermarche.pt/shelves/mercearia/conservas/pickles-e-outros-vegetais/11733",
        "https://www.intermarche.pt/shelves/mercearia/batatas-fritas-e-snacks/batatas-lisas-e-onduladas/10221",
        "https://www.intermarche.pt/shelves/mercearia/batatas-fritas-e-snacks/batatas-com-sabores/10219",
        "https://www.intermarche.pt/shelves/mercearia/batatas-fritas-e-snacks/batatas-palha-e-caseiras/10218",
        "https://www.intermarche.pt/shelves/mercearia/batatas-fritas-e-snacks/snacks-e-aperitivos/10222",
        "https://www.intermarche.pt/shelves/mercearia/batatas-fritas-e-snacks/desidratados-e-frutos-secos/10223",
        "https://www.intermarche.pt/shelves/mercearia/batatas-fritas-e-snacks/pipocas/11726",
        "https://www.intermarche.pt/shelves/bebidas/agua/agua-com-gas/11672",
        "https://www.intermarche.pt/shelves/bebidas/agua/agua-sem-gas/11673",
        "https://www.intermarche.pt/shelves/bebidas/agua/agua-com-sabores/11674",
        "https://www.intermarche.pt/shelves/bebidas/agua/agua-tonica-e-ginger-ale/11675",
        "https://www.intermarche.pt/shelves/bebidas/cervejas-e-sidras/cerveja-branca/11112",
        "https://www.intermarche.pt/shelves/bebidas/cervejas-e-sidras/cerveja-preta/11113",
        "https://www.intermarche.pt/shelves/bebidas/cervejas-e-sidras/cerveja-sem-alcool/10341",
        "https://www.intermarche.pt/shelves/bebidas/cervejas-e-sidras/sidras-e-panaches/10342",
        "https://www.intermarche.pt/shelves/bebidas/cervejas-e-sidras/cervejas-estrangeiras-e-artesanais/11116",
        "https://www.intermarche.pt/shelves/bebidas/refrigerantes-e-sumos/refrigerantes-com-gas/10011",
        "https://www.intermarche.pt/shelves/bebidas/refrigerantes-e-sumos/refrigerantes-sem-gas/10325",
        "https://www.intermarche.pt/shelves/bebidas/refrigerantes-e-sumos/ice-tea-e-tisanas/11109",
        "https://www.intermarche.pt/shelves/bebidas/refrigerantes-e-sumos/nectares-de-fruta/11754",
        "https://www.intermarche.pt/shelves/bebidas/refrigerantes-e-sumos/sumos-100%25/11755",
        "https://www.intermarche.pt/shelves/bebidas/refrigerantes-e-sumos/concentrados-e-em-po/11756",
        "https://www.intermarche.pt/shelves/bebidas/refrigerantes-e-sumos/bebidas-energeticas-e-isotonicas/11111",
        "https://www.intermarche.pt/shelves/bebidas/refrigerantes-e-sumos/agua-tonica-e-ginger-ale/11798",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/leite/leite-meio-gordo/11691",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/leite/leite-gordo/11692",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/leite/leite-magro/11693",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/leite/leite-proteico/11694",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/leite/achocolatados-e-aromatizados/11695",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/leite/leites-infantis-e-bebidas-lacteas/11696",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/leite/sem-lactose/11697",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/leite/bebidas-vegetais/11753",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/ovos/ovos/11698",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/manteiga-e-cremes/manteigas/11706",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/manteiga-e-cremes/cremes-vegetais-e-para-barrar/11707",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/culinaria/natas-culinaria-e-bechamel/11703",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/culinaria/margarinas/11704",
        "https://www.intermarche.pt/shelves/laticinios-e-ovos/culinaria/natas-para-bater-e-chantilly/11705",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/queijo/queijo-fatiado-e-bolas/11551",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/queijo/queijo-ralado-e-para-barrar/11552",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/queijo/queijo-curado-e-amanteigado/11553",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/queijo/snacks/11554",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/queijo/queijo-fresco-e-mozzarella/11555",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/charcutaria/enchidos/11560",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/charcutaria/fiambre-aves/11558",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/charcutaria/fiambre-porco/11559",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/charcutaria/presunto-e-bacon/11556",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/charcutaria/mortadela-paio-e-chouricao/11557",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/charcutaria/salsichas/11561",
        "https://www.intermarche.pt/shelves/charcutaria-e-queijos/charcutaria/especialidades/11562",
        "https://www.intermarche.pt/shelves/padaria-e-pastelaria/padaria/pao-de-forno/11566",
        "https://www.intermarche.pt/shelves/padaria-e-pastelaria/padaria/pao-de-forma-e-embalados/11567",
        "https://www.intermarche.pt/shelves/padaria-e-pastelaria/padaria/tostas-croutons-e-gressinos/11568",
        "https://www.intermarche.pt/shelves/padaria-e-pastelaria/padaria/pao-ralado/11569",
        "https://www.intermarche.pt/shelves/padaria-e-pastelaria/pastelaria/pastelaria-doce/11570",
        "https://www.intermarche.pt/shelves/padaria-e-pastelaria/pastelaria/pastelaria-salgada/11571",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-liquidos/10400",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-aromas-e-naturais/10395",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-pedacos/10396",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-magros/10397",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-bifidus/10398",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-infantis/11178",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-gregos-e-kefir/11176",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-proteicos/11177",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-defesas-e-coracao/11713",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/iogurtes-sem-lactose/11175",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/iogurtes/vegegurtes-e-yofu/11818",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/sobremesas/mousses-e-pudins/10719",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/sobremesas/gelatinas/10800",
        "https://www.intermarche.pt/shelves/iogurtes-e-sobremesas/sobremesas/fruta/11799",
        "https://www.intermarche.pt/shelves/congelados/refeicoes/douradinhos-filetes-e-crocantes/11589",
        "https://www.intermarche.pt/shelves/congelados/refeicoes/hamburguers-e-almondegas/11587",
        "https://www.intermarche.pt/shelves/congelados/refeicoes/entradas-e-salgados/11588",
        "https://www.intermarche.pt/shelves/congelados/refeicoes/pizzas/11584",
        "https://www.intermarche.pt/shelves/congelados/refeicoes/lasanhas-e-massas-italianas/11585",
        "https://www.intermarche.pt/shelves/congelados/refeicoes/refeicoes/11586",
        "https://www.intermarche.pt/shelves/congelados/peixe-e-marisco/peixe/11576",
        "https://www.intermarche.pt/shelves/congelados/peixe-e-marisco/bacalhau/11578",
        "https://www.intermarche.pt/shelves/congelados/peixe-e-marisco/marisco/11577",
        "https://www.intermarche.pt/shelves/congelados/fruta-e-legumes/fruta/11579",
        "https://www.intermarche.pt/shelves/congelados/fruta-e-legumes/legumes/11580",
        "https://www.intermarche.pt/shelves/congelados/fruta-e-legumes/batatas-pre-fritas/11581",
        "https://www.intermarche.pt/shelves/congelados/gelados-e-sobremesas/gelados/11582",
        "https://www.intermarche.pt/shelves/congelados/gelados-e-sobremesas/sobremesas/11583",
        "https://www.intermarche.pt/shelves/congelados/gelo/gelo-picado-e-cubos/11482",
        "https://www.intermarche.pt/shelves/refeicoes/refrigeradas/pizzas-e-lasanhas/11644",
        "https://www.intermarche.pt/shelves/refeicoes/refrigeradas/outras-refeicoes/11645",
        "https://www.intermarche.pt/shelves/refeicoes/refrigeradas/sopas-e-cremes/11646",
        "https://www.intermarche.pt/shelves/refeicoes/refrigeradas/saladas-sandes-e-wraps/11647",
        "https://www.intermarche.pt/shelves/refeicoes/refrigeradas/massas/11648",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-do-douro/11476",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-do-dao/11477",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-das-beiras/11714",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-da-bairrada/11620",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-de-lisboa-e-tejo/11621",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-de-setubal/11622",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-do-alentejo/11623",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-biologicos/11625",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-tintos/tintos-estrangeiros/11626",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-brancos/brancos-do-douro/11478",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-brancos/brancos-do-dao/11479",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-brancos/brancos-das-beiras/11480",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-brancos/brancos-da-bairrada/11627",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-brancos/brancos-de-lisboa-e-tejo/11628",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-brancos/brancos-de-setubal/11629",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-brancos/brancos-do-alentejo/11630",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-brancos/brancos-estrangeiros/11633",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-rose/rose-douro-e-dao/11634",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-rose/rose-tejo-lisboa-e-setubal/11635",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-rose/rose-alentejo-e-algarve/11636",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-verdes/verde-tinto/11651",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-verdes/verde-branco/11652",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-verdes/verde-rose/11653",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-correntes-e-sangrias/corrente-tinto/11655",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-correntes-e-sangrias/corrente-branco/11656",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-correntes-e-sangrias/corrente-rose/11657",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-correntes-e-sangrias/frisante/11658",
        "https://www.intermarche.pt/shelves/garrafeira/vinhos-correntes-e-sangrias/sangria/11659",
        "https://www.intermarche.pt/shelves/garrafeira/licorosos-e-aperitivos/moscatel/11660",
        "https://www.intermarche.pt/shelves/garrafeira/licorosos-e-aperitivos/vinho-do-porto/11661",
        "https://www.intermarche.pt/shelves/garrafeira/licorosos-e-aperitivos/licores/11663",
        "https://www.intermarche.pt/shelves/garrafeira/licorosos-e-aperitivos/aperitivos/11664",
        "https://www.intermarche.pt/shelves/garrafeira/bebidas-espirituosas/vodka/11665",
        "https://www.intermarche.pt/shelves/garrafeira/bebidas-espirituosas/whisky/11666",
        "https://www.intermarche.pt/shelves/garrafeira/bebidas-espirituosas/cocktails-cachaca-tequila-e-rum/11667",
        "https://www.intermarche.pt/shelves/garrafeira/bebidas-espirituosas/gin/11668",
        "https://www.intermarche.pt/shelves/garrafeira/bebidas-espirituosas/aguardente-e-brandy/11669",
        "https://www.intermarche.pt/shelves/garrafeira/champanhe-e-espumantes/champanhes/11670",
        "https://www.intermarche.pt/shelves/garrafeira/champanhe-e-espumantes/espumantes/11671",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-da-cozinha/detergente-maquina-loica/11404",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-da-cozinha/detergente-liquido-loica/11405",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-da-cozinha/limpeza-fogao-e-forno/11407",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-da-cozinha/multisuperficies/11408",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-casa-de-banho/abrasivos/10602",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-casa-de-banho/blocos-e-liquidos-sanitarios/10603",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-casa-de-banho/anticalcarios-e-desinfetantes/10604",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/detergente-lava-tudo/10739",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/detergente-limpa-vidros/11410",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/lixivia/11411",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/multisuperficies/11412",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/desentupidores/11413",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/limpeza-e-cuidados-de-madeiras/11414",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/especificos-de-limpeza/11415",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/panos-esfregoes-e-luvas/11793",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/esfregonas-e-mopas/11794",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/vassouras-escovas-e-pas/11795",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/baldes-e-alguidares/11796",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-geral/sacos-do-lixo/11797",
        "https://www.intermarche.pt/shelves/limpeza/ambientadores/ambientadores-eletricos-e-automaticos/10563",
        "https://www.intermarche.pt/shelves/limpeza/ambientadores/ambientadores-automovel/10564",
        "https://www.intermarche.pt/shelves/limpeza/ambientadores/velas-ambientadoras/10566",
        "https://www.intermarche.pt/shelves/limpeza/ambientadores/absorve-odores/10567",
        "https://www.intermarche.pt/shelves/limpeza/ambientadores/sprays-e-sticks-perfumadores/11792",
        "https://www.intermarche.pt/shelves/limpeza/inseticidas/inseticidas-eletricos-e-automaticos/10569",
        "https://www.intermarche.pt/shelves/limpeza/inseticidas/inseticidas-em-spray-e-fitas/10570",
        "https://www.intermarche.pt/shelves/limpeza/inseticidas/anti-tracas/10571",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/lavagem-e-limpeza-manual/11783",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/detergente-em-po/11784",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/detergente-liquido/11785",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/detergente-em-capsulas-e-pastilhas/11786",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/amaciador/11787",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/aditivos-e-outros-cuidados/11788",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/lixivia/11789",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/limpeza-e-cuidados-do-calcado/11790",
        "https://www.intermarche.pt/shelves/limpeza/limpeza-roupa-e-calcado/lavandaria/11791",
        "https://www.intermarche.pt/shelves/limpeza/guardanapos-e-rolos-de-cozinha/guardanapos/10600",
        "https://www.intermarche.pt/shelves/limpeza/guardanapos-e-rolos-de-cozinha/rolos-de-cozinha/10601",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-oral/pasta-de-dentes/10471",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-oral/escova-de-dentes/10473",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-oral/fios-dentarios/10470",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-oral/elixires/10474",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-oral/produtos-para-proteses-dentarias/10472",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-oral/higiene-oral-infantil/10469",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/cabelo/champos/11758",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/cabelo/condicionadores-e-mascaras/11759",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/cabelo/coloracao/11760",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/cabelo/modeladores/11761",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/cabelo/acessorios/11762",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/rosto-e-maquilhagem/unhas/11764",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/rosto-e-maquilhagem/mascaras-cremes-e-limpeza-facial/11765",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/rosto-e-maquilhagem/olhos-e-rosto/11766",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/rosto-e-maquilhagem/batons/11767",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/corpo/gel-de-banho/10476",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/corpo/sabonetes/10477",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/corpo/cuidados-para-o-corpo/10478",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/corpo/desodorizantes-e-perfumes/10786",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/corpo/depilacao/10475",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/corpo/acessorios/11763",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-intima/pensos-diarios/10538",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-intima/pensos-higienicos/10539",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-intima/tampoes/10540",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-intima/gel-e-locoes/10541",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-intima/toalhitas-intimas/10698",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/higiene-intima/incontinencia/11768",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/homem/barba/11316",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/homem/rosto/11317",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/homem/cabelo/11318",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/homem/gel-de-banho/11383",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/homem/desodorizantes-e-perfumes/11325",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/homem/depilacao/11322",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/produtos-solares/bronzeadores/10529",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/produtos-solares/protetores/10530",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/produtos-solares/after-sun/10528",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/produtos-solares/crianca/11777",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/bem-estar-e-cuidados/cuidados-de-saude/11400",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/bem-estar-e-cuidados/desinfetantes/11401",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/bem-estar-e-cuidados/baton-e-balsamos/11402",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/bem-estar-e-cuidados/cotonetes-e-soro-fisiologico/11778",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/bem-estar-e-cuidados/preservativos-e-outros/11779",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/papel-higienico-e-lencos-papel/papel-higienico/11780",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/papel-higienico-e-lencos-papel/lencos-de-papel/11781",
        "https://www.intermarche.pt/shelves/higiene-e-beleza/papel-higienico-e-lencos-papel/toalhitas/11782",
        "https://www.intermarche.pt/shelves/bebe/alimentacao/leites-infantis/11595",
        "https://www.intermarche.pt/shelves/bebe/alimentacao/papas-infantis/11596",
        "https://www.intermarche.pt/shelves/bebe/alimentacao/alimentos-lacteos/11597",
        "https://www.intermarche.pt/shelves/bebe/alimentacao/boioes-saquetas-e-pures-de-fruta/11598",
        "https://www.intermarche.pt/shelves/bebe/alimentacao/snacks-e-bolachinhas/11599",
        "https://www.intermarche.pt/shelves/bebe/higiene/fraldas/11601",
        "https://www.intermarche.pt/shelves/bebe/higiene/toalhitas/11602",
        "https://www.intermarche.pt/shelves/bebe/higiene/banho/11603",
        "https://www.intermarche.pt/shelves/bebe/higiene/higiene-oral/11604",
        "https://www.intermarche.pt/shelves/bebe/higiene/protecao-e-hidratacao/11605",
        "https://www.intermarche.pt/shelves/bebe/puericultura-e-brinquedos/bacios-e-redutores/11606",
        "https://www.intermarche.pt/shelves/bebe/puericultura-e-brinquedos/banheiras-e-outros-acessorios/11607",
        "https://www.intermarche.pt/shelves/bebe/puericultura-e-brinquedos/brinquedos-primeira-idade/11608",
        "https://www.intermarche.pt/shelves/bebe/puericultura-e-brinquedos/chupetas-e-acessorios-de-alimentacao/11609",
        "https://www.intermarche.pt/shelves/bebe/puericultura-e-brinquedos/toalhas-roupoes-resguardos-e-mantas/11613",
        "https://www.intermarche.pt/shelves/animais/cao/racao-seca/10659",
        "https://www.intermarche.pt/shelves/animais/cao/comida-humida/10658",
        "https://www.intermarche.pt/shelves/animais/cao/snacks-e-biscoitos/10660",
        "https://www.intermarche.pt/shelves/animais/cao/higiene/10661",
        "https://www.intermarche.pt/shelves/animais/cao/acessorios-e-brinquedos/10657",
        "https://www.intermarche.pt/shelves/animais/gato/racao-seca/10663",
        "https://www.intermarche.pt/shelves/animais/gato/comida-humida/10662",
        "https://www.intermarche.pt/shelves/animais/gato/snacks-e-biscoitos/10664",
        "https://www.intermarche.pt/shelves/animais/gato/areias-e-higiene/10666",
        "https://www.intermarche.pt/shelves/animais/gato/acessorios-e-brinquedos/10665",
        "https://www.intermarche.pt/shelves/animais/outros-animais/passaros/11263",
        "https://www.intermarche.pt/shelves/animais/outros-animais/roedores/11266",
        "https://www.intermarche.pt/shelves/papelaria/material-escolar-e-escritorio/cadernos-blocos-e-papel/11491",
        "https://www.intermarche.pt/shelves/papelaria/material-escolar-e-escritorio/escrita/11492",
        "https://www.intermarche.pt/shelves/papelaria/material-escolar-e-escritorio/organizacao-e-arquivo/11493",
        "https://www.intermarche.pt/shelves/papelaria/material-escolar-e-escritorio/desenho-pintura-e-moldes/11494",
        "https://www.intermarche.pt/shelves/papelaria/material-escolar-e-escritorio/mochilas-e-estojos/11495",
        "https://www.intermarche.pt/shelves/papelaria/material-escolar-e-escritorio/material-de-escritorio/11496"
]

PAGE_SIZE = 50

categories = [u.rstrip("/").split("/")[-1] for u in targetUrls]
products_out = []

for category in categories:
    page = 1

    while True:

        payload = {
            "category": category,
            "page": page,
            "size": PAGE_SIZE,
            "filtres": [],
            "tri": "pertinence",
            "ordreTri": "decroissant",
            "catalog": ["PDV"]
        }

        print(f"Fetching page {page}")

        r = requests.post(URL, headers=HEADERS, cookies=COOKIES, json=payload)

        if r.status_code != 200:
            print("Request failed:", r.status_code)
            break

        data = r.json()

        produits = data.get("produits", [])

        if not produits:
            break

        for p in produits:

            product = {
                "retailer": "Intermarché",
                "id": str(p.get("identifier")),
                "ean": p.get("produitEan13"),
                "brand": p.get("marque"),
                "product_name": p.get("libelle"),
                "price": p.get("prix"),
                "price_per_unit": f"{p.get('prixKg')} €/Kg" if p.get("prixKg") else None,
                "qty": p.get("conditionnement"),
                "is_promo": p.get("prixBarre", 0) > 0,
                "promo_info": None,
                "offer_expires": None,
                "origin": p.get("origine"),
                "image_url": p.get("images")[0] if p.get("images") else None,
                "product_url": f"https://www.intermarche.pt/product/{p.get('libelle').lower().replace(' ','-')}/{p.get('produitEan13')}",
                "scraped_at": datetime.now(timezone.utc).isoformat()
            }

            products_out.append(product)

        page += 1
        time.sleep(0.3)

print(f"Collected {len(products_out)} products")

with open("data/intermarche/products.json", "w", encoding="utf-8") as f:
    json.dump(products_out, f, indent=2, ensure_ascii=False)

print("Saved to products.json")