# scrapy crawl continenteData -O ../../../data/continente/data_test.json 

import scrapy
import json
import os
from urllib.parse import urlparse, urlunparse, parse_qs, urlencode

class ContinentDataExtractor(scrapy.Spider):
    name = "continenteData_backup"
    
    custom_settings = {
        'ROBOTSTXT_OBEY': False,
        'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
        'CONCURRENT_REQUESTS': 2,
        'FEED_EXPORT_ENCODING': 'utf-8',
    }

    def __init__(self, *args, **kwargs):
        super(ContinentDataExtractor, self).__init__(*args, **kwargs)
        
        # Path to the metadata file generated by your helper script
        metadata_file = 'spiders/continente_metadata.json'
        
        if os.path.exists(metadata_file):
            with open(metadata_file, 'r', encoding='utf-8') as f:
                self.categories = json.load(f)
            self.logger.info(f"Loaded {len(self.categories)} categories from {metadata_file}")
        else:
            self.categories = []
            self.logger.error(f"Metadata file {metadata_file} NOT FOUND.")

    def start_requests(self):
        for cat in self.categories:
            # The URL already contains start=0, srule, etc.
            yield scrapy.Request(
                url=cat['url'],
                callback=self.parse,
                meta={
                    'cat_config': cat,
                    'current_start': 0 
                }
            )

    def parse(self, response):
        cat_config = response.meta['cat_config']
        current_start = response.meta['current_start']
        
        self.logger.info(f"Processing {cat_config['name']} | Offset: {current_start}")

        # Select valid product tiles using the impression data attribute
        products = response.xpath("//div[contains(@class, 'product-tile') and @data-product-tile-impression]")
        
        for product in products:
            json_data = product.xpath("./@data-product-tile-impression").get()
            
            if json_data:
                try:
                    item = json.loads(json_data)
                    if item.get('name'):
                        item['scraped_category'] = cat_config['name']
                        
                        # Extract quantity (e.g., "Emb. 500 g")
                        quantity = product.xpath(".//p[contains(@class, 'pwc-tile--quantity')]/text()").get()
                        item['quantity_label'] = quantity.strip() if quantity else ""
                        
                        # Extract display price (primary price shown on site)
                        display_price = product.xpath(".//span[contains(@class, 'pwc-tile--price-primary')]//text()").getall()
                        item['display_price'] = "".join(display_price).strip() if display_price else f"{item.get('price')} €"
                        
                        # Product URL
                        rel_url = product.xpath(".//a[contains(@class, 'pwc-tile--description')]/@href").get()
                        item['url'] = response.urljoin(rel_url) if rel_url else ""

                        yield item
                except json.JSONDecodeError:
                    continue 

        # --- Dynamic Pagination Logic ---
        next_start = current_start + cat_config['productsPerPage']

        if next_start < cat_config['totalProducts']:
            # We parse the current URL and swap out only the 'start' parameter
            # This preserves srule, pmin, and any other filters
            parsed_url = urlparse(response.url)
            query_params = parse_qs(parsed_url.query)
            query_params['start'] = [str(next_start)] # Update the offset
            
            # Reconstruct the URL
            new_query = urlencode(query_params, doseq=True)
            next_url = urlunparse(parsed_url._replace(query=new_query))
            
            yield response.follow(
                next_url, 
                callback=self.parse,
                meta={
                    'cat_config': cat_config, 
                    'current_start': next_start
                }
            )